Rename classes
UMM-CSci-3601-F17/iteration-2-cheezit pull request #88
Opened 2017-12-02 23:57 UTC by bushw011

It makes a simple call to the database that updates the classname. The UI for this is an edit button next to the class title that only appears for teachers. This button allows them to do an inline (no dialog popup) edit of the name. Closes #39

|![localhost_9000_class_p7w93wrki44pzqxnkiqw iphone 6](https://user-images.githubusercontent.com/25711751/33520931-f0e5639e-d789-11e7-9b41-b5b17b68eafb.png)|
![localhost_9000_class_p7w93wrki44pzqxnkiqw iphone 6 1](https://user-images.githubusercontent.com/25711751/33520932-f3a29e3a-d789-11e7-8db5-f9545314893c.png)|
![localhost_9000_class_p7w93wrki44pzqxnkiqw iphone 6 2](https://user-images.githubusercontent.com/25711751/33520933-f6faddfe-d789-11e7-8ed6-f5eb2522855a.png)|
|---|---|---|

2017-12-03 00:09 UTC, floogulinc commented on src/app/class-component/class.component.ts
> +    public updateClass(): void {
should probably be called renameClass

2017-12-03 00:09 UTC, floogulinc commented on src/app/class/class.service.ts
> +    public editClass(classId: string, newClassName: string){
should probably be called renameClass

2017-12-03 02:56 UTC, EthanUphoff submitted a review, later dismissed
Looks good to me, runs well, no bugs found.

2017-12-03 03:13 UTC, floogulinc requested changes
The menu icon shouldn't move when editing a card on mobile as it does in the screenshot.

2017-12-03 06:34 UTC, floogulinc requested changes

2017-12-03 06:34 UTC, floogulinc commented on src/app/class-component/class.component.css
> +.mat-form-field.class-edit-field{
This only needs to select the class, not `.mat-form-field`

2017-12-03 06:35 UTC, floogulinc requested changes

2017-12-03 06:35 UTC, floogulinc commented on src/app/class-component/class.component.html
> +                    <mat-form-field class="class-edit-field" id="class-edit-field" *ngIf="editing">
We don't need both an ID and a class

2017-12-04 01:50 UTC, floogulinc submitted a review, later dismissed

2017-12-04 01:51 UTC, floogulinc commented
We should merge this in first and use the new component in renaming decks (#20 and #89)

2017-12-04 01:58 UTC, floogulinc approved these changes
Looks good now!

2017-12-04 02:10 UTC, merged